  - job_name: cadvisor
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: https
    kubernetes_sd_configs:
    - api_server: https://kubernetes.default:8443
      role: node
      bearer_token: '<paste_the_service_token_here>'
      tls_config:
        insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true

    bearer_token: '<paste_the_service_token_here>'
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default:8443
      - source_labels: [kubernetes_io_hostname]
        target_label: __metrics_path__
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor